name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake
    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Run tests
      run: ${{github.workspace}}/build/threadpooluniverselib_test
